### PR TITLE
add entry for release qualification pipeline

### PR DESCRIPTION
**Pull request by richardwxn**
WIP, pending on local testing and corresponding change in tools repo to publish data

/CC @mandarjog

### CODE REVIEW

**Comment by richardwxn** [comment]
@therealmitchconnors Can I get an initial review on this and https://github.com/istio/tools/pull/1205/files

**Comment by ericvn** [comment]
Will need a `gofmt -s -w ` done against: policybot/pkg/storage/types.go and policybot/dashboard/topics/releasequalification/topic.go to get the changes to satisfy the lint. `make fmt` doesn't currently fix problems with files with missing newlines at the end and possible spaces at the end of lines.

**Review by therealmitchconnors — APPROVED** [review]
golang and SQL look good.  I'm not the best to review html, but it appears good!

**Pull request merged**
