### PR TITLE
Add istio.io website dashboard to eng.istio.io

### PR DESCRIPTION
**Pull request by niwatorrri**
Istio.io website dashboard is embedded on eng.istio.io/website

### CODE REVIEW

**Comment by niwatorrri** [comment]
cc @davidhauck @therealmitchconnors @nmittler

**Comment by niwatorrri** [comment]
@davidhauck How about "Istio.io Web Analytics"?

**Comment by davidhauck** [comment]
I was talking about the package name specifically, but that would be good for the entry name!

**Comment by niwatorrri** [comment]
I changed package name to "webanalytics" which should hopefully sound better

**Pull request merged**
