### PR TITLE
Remove community-[help-wanted/good-first-issue] labels

### PR DESCRIPTION
**Pull request by kfaseela**
Now that we have created `help wanted` and `good first issue` labels and migrated all existing issues to use the new labels, let us remove the old labels

### CODE REVIEW

**Comment by ericvn** [comment]
DNM as there are still some issues with the old labels.

**Comment by kfaseela** [comment]
Fixed community and istio.io repos.

**Comment by ericvn** [comment]
Looks like the labels are no longer in use.

**Review by ericvn — APPROVED** [review]
Thanks,

**Pull request merged**
